export const home = '/'
export const about = '/about'
export const profile = '/profile'
export const locations = '/my-locations'
export const signUp = '/sign-up'
export const forgotPassword = '/forgot-password'
export const addLocation = '/add-location'
export const editLocation = '/edit-location/:id'
